# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'maskn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for maskn
  pod 'TwitterKit'
  pod 'TwitterCore'

  target 'maskn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'masknTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

